name: Build and Deploy Docker image (Admin Service)

on:
  push:
    branches:
      - main

jobs:
  args:
    runs-on: ubuntu-24.04
    outputs:
      encrypted_docker_image_name: ${{ steps.encrypted.outputs.encrypted_docker_image_name }}
      commit_short_sha: ${{ steps.sha.outputs.SHORT_SHA }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get lowercase repo name
        id: repo_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}

      - name: Encrypt repo name
        id: encrypted
        run: |
          PLAIN_TEXT=${{ steps.repo_name.outputs.lowercase }}
          BINARY_ENCRYPTED=$(echo -n "$PLAIN_TEXT" | openssl enc -aes-256-cbc -pbkdf2 -salt -k "${{ secrets.ENCRYPTION_PASSWORD }}")
          ENCRYPTED=$(echo -n "$BINARY_ENCRYPTED" | base64)
          echo "encrypted_docker_image_name=$ENCRYPTED" >> $GITHUB_OUTPUT

  build-docker:
    runs-on: ${{ matrix.os }}
    needs:
      - args
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

    env:
      BUILDX_CACHE_PATH: /tmp/buildx-cache
      BUILDX_CACHE_NAME: buildx-cache

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Load arguments
        id: args
        run: |
          ENCRYPTED=${{ needs.args.outputs.encrypted_docker_image_name }}
          BINARY_ENCRYPTED=$(echo -n "$ENCRYPTED" | base64 --decode)
          DECRYPTED=$(echo -n "$BINARY_ENCRYPTED" | openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.ENCRYPTION_PASSWORD }}")
          echo "COMMIT_SHORT_SHA=${{ needs.args.outputs.commit_short_sha }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=$DECRYPTED" >> $GITHUB_ENV

      - name: Load cache if available
        uses: actions/cache@v4
        id: load_cache
        with:
          path: ${{ env.BUILDX_CACHE_PATH }}
          key: ${{ env.BUILDX_CACHE_NAME }}-${{ matrix.os }}-${{ matrix.arch }}-${{ env.COMMIT_SHORT_SHA }}
          restore-keys: |
            ${{ env.BUILDX_CACHE_NAME }}-${{ matrix.os }}-${{ matrix.arch }}-
            ${{ env.BUILDX_CACHE_NAME }}-${{ matrix.os }}-
            ${{ env.BUILDX_CACHE_NAME }}-

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker build environment
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - run: |
          ls -alh

      - name: Build Image (per architecture)
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=local,src=${{ env.BUILDX_CACHE_PATH }}
          cache-to: type=local,dest=${{ env.BUILDX_CACHE_PATH }},mode=max,compression=zstd
          platforms: linux/${{ matrix.arch }}
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.COMMIT_SHORT_SHA }}-${{ matrix.arch }}

  merge-image-manifest:
    runs-on: ubuntu-latest
    needs:
      - args
      - build-docker
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Load arguments
        id: args
        run: |
          ENCRYPTED=${{ needs.args.outputs.encrypted_docker_image_name }}
          BINARY_ENCRYPTED=$(echo -n "$ENCRYPTED" | base64 --decode)
          DECRYPTED=$(echo -n "$BINARY_ENCRYPTED" | openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.ENCRYPTION_PASSWORD }}")
          echo "COMMIT_SHORT_SHA=${{ needs.args.outputs.commit_short_sha }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=$DECRYPTED" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push manifest list
        run: |
          docker buildx imagetools create \
            -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.COMMIT_SHORT_SHA }} \
            -t ${{ env.DOCKER_IMAGE_NAME }}:dev \
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.COMMIT_SHORT_SHA }}-amd64 \
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.COMMIT_SHORT_SHA }}-arm64

  trigger-deploy-infra:
    runs-on: ubuntu-latest
    needs:
      - merge-image-manifest
    steps:
      - name: Dispatch event for Admin Deployment
        if: ${{ github.repository_owner == 'Snail-Official' }}
        run: gh api /repos/snail-official/nailian-iac/dispatches -f event_type='restart-admin-dev'
        env:
          GH_TOKEN: ${{ secrets.GH_TRIGGER_TOKEN }}
