name: Build and Deploy Docker image (Admin Service)

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get lowercase repo name
        id: repo_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}

      - run: echo "BUILDX_CACHE_PATH=/tmp/buildx-cache" >> $GITHUB_ENV

      - name: Load cache if available
        uses: actions/cache/restore@v4
        id: load_cache
        with:
          path: ${{ env.BUILDX_CACHE_PATH }}
          key: buildx-cache-${{ matrix.os }}-${{ matrix.arch }}

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker build environment
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build Image (per architecture)
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=local,src=${{ env.BUILDX_CACHE_PATH }}
          cache-to: type=local,dest=${{ env.BUILDX_CACHE_PATH }},mode=max,compression=zstd
          platforms: linux/${{ matrix.arch }}
          tags: |
            ${{ steps.repo_name.outputs.lowercase }}:${{ steps.sha.outputs.SHORT_SHA }}-${{ matrix.arch }}

      - name: Load cache if available
        uses: actions/cache/save@v4
        id: save_cache
        with:
          path: ${{ env.BUILDX_CACHE_PATH }}
          key: ${{ steps.load_cache.outputs.cache-primary-key }}

  merge-image-manifest:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-docker
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get lowercase repo name
        id: repo_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push manifest list
        run: |
          docker buildx imagetools create \
            -t ${{ steps.repo_name.outputs.lowercase }}:${{ steps.sha.outputs.SHORT_SHA }} \
            -t ${{ steps.repo_name.outputs.lowercase }}:dev \
            ${{ steps.repo_name.outputs.lowercase }}:${{ steps.sha.outputs.SHORT_SHA }}-amd64 \
            ${{ steps.repo_name.outputs.lowercase }}:${{ steps.sha.outputs.SHORT_SHA }}-arm64

  trigger-deploy-infra:
    runs-on: ubuntu-latest
    needs:
      - merge-image-manifest
    steps:
      - name: Dispatch event for Admin Deployment
        run: gh api /repos/snail-official/nailian-iac/dispatches -f event_type='restart-admin-dev'
        env:
          GH_TOKEN: ${{ secrets.GH_TRIGGER_TOKEN }}
